spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/profind
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: google
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
key: javadocsdsadsafgsdag4aergdfsagdfgfdgrgredasdasdsadsa
server:
  port: 8081